---
- name: update apt
  become: yes
  apt: update_cache=yes

- name: install chromedriver dependencies
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - libnss3
    - libgconf-2-4

- name: get chromedriver latest version number
  uri:
    url: "{{ chromedriver_version_url }}"
    return_content: yes
    headers:
      Content-Type: "text/plain"
  register: latest_chromedriver

- name: download chromedriver
  become: yes
  unarchive:
    src: "https://chromedriver.storage.googleapis.com/{{ latest_chromedriver.content|trim }}/chromedriver_linux64.zip"
    dest: /usr/local/bin
    remote_src: yes
